se crean carpeta api y client, y se agrega mercado pago
EatOutPF/EatOut pull request #5
Opened 2023-03-18 20:05 UTC by DianaCanon

se crean carpentas de api y client , se crean un front sencillo para implemntar mercado pago, que afecta tanto backend como frontend

2023-03-18 20:16 UTC, LordPock requested changes
agregar el archivo .gitignore y vuelve a hacer el commit, asi no se suben el node_module y el .env

2023-03-18 20:54 UTC, DianaCanon commented
listo el cambio

2023-03-18 20:58 UTC, LordPock approved these changes

2023-03-18 20:58 UTC, merged

2023-03-19 14:42 UTC, SantiBavaresco commented
Aprobado